# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{podium}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["tsaleh"]
  s.date = %q{2010-03-03}
  s.description = %q{HAML and JS based presentation system.}
  s.email = %q{tsaleh@gmail.com}
  s.executables = ["podium", "showoff2podium"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/podium",
     "bin/showoff2podium",
     "lib/podium.rb",
     "lib/podium/commands.rb",
     "lib/podium/haml_filters.rb",
     "lib/podium/helpers.rb",
     "podium.gemspec",
     "templates/assets/local.css",
     "templates/assets/suspenders.png",
     "templates/index.html.haml",
     "templates/podium/css/code.css",
     "templates/podium/css/slides.css",
     "templates/podium/javascript/code_highlighter/base.js",
     "templates/podium/javascript/code_highlighter/css.js",
     "templates/podium/javascript/code_highlighter/html.js",
     "templates/podium/javascript/code_highlighter/index.html",
     "templates/podium/javascript/code_highlighter/javascript.js",
     "templates/podium/javascript/code_highlighter/ruby.js",
     "templates/podium/javascript/code_highlighter/stylesetguide.html",
     "templates/podium/javascript/code_highlighter/test.html",
     "templates/podium/javascript/jquery-1.4.1.js",
     "templates/podium/javascript/slides.js",
     "templates/podium/layout.html.haml"
  ]
  s.homepage = %q{http://github.com/tsaleh/podium}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{HAML and JS based presentation system.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<haml>, [">= 2.2.0"])
    else
      s.add_dependency(%q<haml>, [">= 2.2.0"])
    end
  else
    s.add_dependency(%q<haml>, [">= 2.2.0"])
  end
end

