# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{podium}
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["tsaleh"]
  s.date = %q{2010-05-05}
  s.description = %q{Haml and JS based presentation system.}
  s.email = %q{tsaleh@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/podium.rb",
     "lib/podium/haml_filters.rb",
     "lib/podium/helpers.rb",
     "lib/podium/internal_assets.rb",
     "lib/podium/slides.rb",
     "podium.gemspec",
     "public/javascripts/code_highlighter/base.js",
     "public/javascripts/code_highlighter/css.js",
     "public/javascripts/code_highlighter/html.js",
     "public/javascripts/code_highlighter/index.html",
     "public/javascripts/code_highlighter/javascript.js",
     "public/javascripts/code_highlighter/ruby.js",
     "public/javascripts/code_highlighter/stylesetguide.html",
     "public/javascripts/code_highlighter/test.html",
     "public/javascripts/jquery-1.4.1.js",
     "public/javascripts/jquery-ui-1.8.js",
     "public/javascripts/local.js",
     "public/javascripts/slides.js",
     "public/stylesheets/blueprint/ie.css",
     "public/stylesheets/blueprint/plugins/buttons/icons/cross.png",
     "public/stylesheets/blueprint/plugins/buttons/icons/key.png",
     "public/stylesheets/blueprint/plugins/buttons/icons/tick.png",
     "public/stylesheets/blueprint/plugins/buttons/readme.txt",
     "public/stylesheets/blueprint/plugins/buttons/screen.css",
     "public/stylesheets/blueprint/plugins/fancy-type/readme.txt",
     "public/stylesheets/blueprint/plugins/fancy-type/screen.css",
     "public/stylesheets/blueprint/plugins/link-icons/icons/doc.png",
     "public/stylesheets/blueprint/plugins/link-icons/icons/email.png",
     "public/stylesheets/blueprint/plugins/link-icons/icons/external.png",
     "public/stylesheets/blueprint/plugins/link-icons/icons/feed.png",
     "public/stylesheets/blueprint/plugins/link-icons/icons/im.png",
     "public/stylesheets/blueprint/plugins/link-icons/icons/pdf.png",
     "public/stylesheets/blueprint/plugins/link-icons/icons/visited.png",
     "public/stylesheets/blueprint/plugins/link-icons/icons/xls.png",
     "public/stylesheets/blueprint/plugins/link-icons/readme.txt",
     "public/stylesheets/blueprint/plugins/link-icons/screen.css",
     "public/stylesheets/blueprint/plugins/rtl/readme.txt",
     "public/stylesheets/blueprint/plugins/rtl/screen.css",
     "public/stylesheets/blueprint/print.css",
     "public/stylesheets/blueprint/screen.css",
     "public/stylesheets/blueprint/src/forms.css",
     "public/stylesheets/blueprint/src/grid.css",
     "public/stylesheets/blueprint/src/grid.png",
     "public/stylesheets/blueprint/src/ie.css",
     "public/stylesheets/blueprint/src/print.css",
     "public/stylesheets/blueprint/src/reset.css",
     "public/stylesheets/blueprint/src/typography.css",
     "public/stylesheets/code.css",
     "public/stylesheets/local.css",
     "public/stylesheets/slides.css",
     "views/layout.haml"
  ]
  s.homepage = %q{http://github.com/tsaleh/podium}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Haml and JS based presentation system.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<haml>, ["~> 2.2.0"])
      s.add_runtime_dependency(%q<sinatra>, [">= 0.9.0"])
      s.add_runtime_dependency(%q<sinatra-static-assets>, [">= 0.5.0"])
    else
      s.add_dependency(%q<haml>, ["~> 2.2.0"])
      s.add_dependency(%q<sinatra>, [">= 0.9.0"])
      s.add_dependency(%q<sinatra-static-assets>, [">= 0.5.0"])
    end
  else
    s.add_dependency(%q<haml>, ["~> 2.2.0"])
    s.add_dependency(%q<sinatra>, [">= 0.9.0"])
    s.add_dependency(%q<sinatra-static-assets>, [">= 0.5.0"])
  end
end

